### PR TITLE
Remove version from composer.json

### PR DESCRIPTION
**Pull request by marcusmoore88**
As commented previously.

### CODE REVIEW

**Comment by rtconner** [comment]
Thanks!

**Comment by rtconner** [comment]
So .. the packagist version number .. it's gotta be a quirk on the part of https://packagist.org
Kind of annoys my the version is not updating there. I think it's because I had removed the master branch in favor of the two laravel branches. I've set laravel-5 as the primary branch. But packagist seems to not respond to that as it should.

**Comment by rtconner** [comment]
I sent packagist an email. Hopefully they respond.

**Comment by marcusmoore88** [comment]
In their update schedule section [here](https://packagist.org/about) they mention that packages without the webhook will be crawled once a day. Maybe that's an issue and once the crawler comes back through it'll pick up on the new primary branch?

**Comment by rtconner** [comment]
I have webhook setup.

**Comment by marcusmoore88** [comment]
Ah...well then...

If you can, comment back with what Packagist's solution is. I'm interested to see how this ends.

**Comment by rtconner** [comment]
.. no response. Dunno. I added version 1.0.2 .. and packagist accepted that version and published it just fine. So .. I really don't know the issue. Maybe packagist just hates the version "1.0.1" Haha. :stuck_out_tongue_winking_eye:

**Comment by marcusmoore88** [comment]
Noted: Never bump to version 1.0.1. Go straight to 1.0.2.

Ha thanks for replying. Glad it got fixed...somehow.

**Pull request merged**
