### PR TITLE
Added persian character maps

### PR DESCRIPTION
**Pull request by AmirMehrabi**
Hello,
Thank you for this amazing package.

So when I tried to use this package, I realized my Persian/Farsi strings wouldn't process as they should, and as a result, my slugs were all messed up. So I added Persian character maps to the "slug" method.

Please take a look, see if it's any good.

### CODE REVIEW

**Comment by AmirMehrabi** [comment]
This is the new PR that I opened. Can you check it my man? @rtconner

**Comment by AmirMehrabi** [comment]
Sorry to bother, just wanted to remind you of this PR my man. @rtconner

**Comment by kossmoss** [comment]
Actually I wonder why this package uses its' own slug method and does not simply reuse Illuminate\Support\Str::slug for that out of the-box

**Comment by rtconner** [comment]
> I'd rather simply reuse Illuminate\Support\Str::slug for that

You can use the config file to set whatever slug method you wanted.
https://github.com/rtconner/laravel-tagging/blob/laravel-8/config/tagging.php#L9

**Comment by AmirMehrabi** [comment]
What do you think about this merge request? @rtconner 
Do you think it qualifies for a merge?

**Comment by rtconner** [comment]
I didn't think it did qualified, it overlaps a lot with per-existing modifiers.

**Pull request closed without merging**
