### PR TITLE
add locale in Tag model

### PR DESCRIPTION
**Pull request by Xoshbin**

### CODE REVIEW

**Review by rtconner — APPROVED** [review]

**Comment by rtconner** [comment]
There is some small cleanups to do with this. I will work on it soon and hopefully tag a 5.x in the next week.

**Comment by Xoshbin** [comment]
Thank you

**Comment by rtconner** [comment]
Man you didn't write any unit tests or anything for this.

What is the use case. I don't understand how to use it.

**Comment by Xoshbin** [comment]
Sorry about that, I'm not used to tests, And about the use case, it's clear that if you have an application with different locales, you need to separate the tags.
I will check if I can add tests, but no promising because as I said I don't do tests 😊

**Comment by rtconner** [comment]
Can you just paste some usage examples in here? I can write tests from them. Just show me how to use it.

**Comment by rtconner** [comment]
Yes but then what?

Do you fetch tags for only that locale? Should we add methods to help with that?

**Comment by Xoshbin** [comment]
Well, I'm sorry about that the code is not complete, I didn't implement that since I'm mostly using it to filter the tags based on the locales from the database level just for for some kind of research. but in other scenarios yes we should add methods to fetch the tags based on the current locale of the website.

**Pull request merged**
